name: Auto Approve PRs
on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto-approve the Pull Request
        uses: hmarr/auto-approve-action@v4
        with:
          # This forces the action to explicitly use the GitHub Actions Bot identity
          github-token: ${{ secrets.GITHUB_TOKEN }}
